## Feature Scalling 
- some times the data from different columns varies alot
- in such dataset machine learning model will pick the column with larger values and ignore the other
- to avoid such we use feature scaling
- there are two types of scalling

## 1:Z-score scalling
- scales data so that the entire column's mean is 0

## 2:min_max scallling
- scales data between 0 and 1

In [38]:
import pandas as pd
df=pd.read_csv('telecom_customer.csv')
# we will just observe the monthly income and bill
df[['monthly_income','monthly_bill']].head()

   monthly_income  monthly_bill
0         57643.0       10049.0
1         18207.0        2752.0
2         13075.0        3155.0
3         38890.0        5859.0
4         17475.0        5106.0

In [39]:
# data information
df[['monthly_income','monthly_bill']].describe()

       monthly_income  monthly_bill
count     1200.000000   1200.000000
mean     31155.975833   5939.150833
std      19351.937726   4046.473963
min       4984.000000    710.000000
25%      17795.000000   3291.750000
50%      26628.000000   4871.000000
75%      39886.250000   7485.500000
max     209790.000000  36361.000000

In [40]:
# as we can see the values varies by 1 figure one is in 1000s and the other in 10000s
# we wll use z-score for monthly income and min_max for monthly bill

## Monthly income scalling with z-score
- z-score = (value-meanOFColumn)/standard_deviation

In [41]:
income_mean=df['monthly_income'].mean()
income_std=df['monthly_income'].std()
print(income_mean,income_std)

31155.975833333334 19351.937725889493

In [42]:
# applying z-score
df['monthly_zscore_income']=(df['monthly_income']-income_mean)/income_std
df[['monthly_income','monthly_zscore_income']].head()

   monthly_income  monthly_zscore_income
0         57643.0               1.368701
1         18207.0              -0.669131
2         13075.0              -0.934324
3         38890.0               0.399651
4         17475.0              -0.706956

In [43]:
df=df.drop(['monthly_income'],axis=1) #no need of the original income column now
df.head(2)

,customer_id,signup_date,age,gender,city,education_level,employment_status,monthly_bill,internet_usage_gb,call_minutes,contract_type,support_tickets,customer_feedback,churn,monthly_zscore_income
0,10001,2019-01-01,65,Male,Multan,Bachelor,Employed,10049.0,5.8,52.0,6-Month,1,Coverage is poor in my location,0,1.368701
1,10002,2019-01-02,22,Female,Peshawar,Master,Employed,2752.0,11.9,22.0,6-Month,2,Billing issues occurred multiple times,0,-0.669131

## Scalling Monthly Bill with min_max scalling
- min_max= (value-MinValue)/(maxValue-MinValue)

In [44]:
bill_min=df['monthly_bill'].min()
bill_max=df['monthly_bill'].max()
print(bill_min,bill_max)

710.0 36361.0

In [45]:
# Applying the min_max formula
df['monthly_minmax_bill']=(df['monthly_bill']-bill_min)/(bill_max-bill_min)
df[['monthly_bill','monthly_minmax_bill']].head()

   monthly_bill  monthly_minmax_bill
0       10049.0             0.261956
1        2752.0             0.057277
2        3155.0             0.068582
3        5859.0             0.144428
4        5106.0             0.123306

In [46]:
# no need of original monthly_bill column
df=df.drop(['monthly_bill'],axis=1)
df.head(2)

,customer_id,signup_date,age,gender,city,education_level,employment_status,internet_usage_gb,call_minutes,contract_type,support_tickets,customer_feedback,churn,monthly_zscore_income,monthly_minmax_bill
0,10001,2019-01-01,65,Male,Multan,Bachelor,Employed,5.8,52.0,6-Month,1,Coverage is poor in my location,0,1.368701,0.261956
1,10002,2019-01-02,22,Female,Peshawar,Master,Employed,11.9,22.0,6-Month,2,Billing issues occurred multiple times,0,-0.669131,0.057277

## comparing the scalled monthly income and bill

In [47]:
df[['monthly_zscore_income','monthly_minmax_bill']].head(15)
# now the values of both columns are scalled near 0 and 1 and the model will not drop either one

    monthly_zscore_income  monthly_minmax_bill
0                1.368701             0.261956
1               -0.669131             0.057277
2               -0.934324             0.068582
3                0.399651             0.144428
4               -0.706956             0.123306
5                0.266538             0.166980
6                1.138130             0.152478
7                0.449775             0.058231
8               -0.521910             0.123026
9                0.318626             0.118622
10              -0.690369             0.039550
11              -0.378876             0.175227
12               0.083507             0.384365
13              -0.270204             0.044936
14               0.334386             0.117837

In [48]:
df[['monthly_zscore_income','monthly_minmax_bill']].describe()

       monthly_zscore_income  monthly_minmax_bill
count           1.200000e+03          1200.000000
mean           -1.628327e-17             0.146676
std             1.000000e+00             0.113502
min            -1.352421e+00             0.000000
25%            -6.904206e-01             0.072417
50%            -2.339805e-01             0.116715
75%             4.511318e-01             0.190051
max             9.230808e+00             1.000000

#### All in the range of 0 and 1 now