**Task 1 churn modeling dataset**

In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,log_loss  #log_loss was lab requirement

**reading data**

In [2]:
df=pd.read_csv('./Churn_Modelling - Churn_Modelling.csv')
print(df.shape)  #1000 ROWS AND 14 Columns
df.head()

(10000, 14)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

**Remove columns that are not important**

In [3]:
df=df.drop(df.columns[:3],axis=1) # axis=1 means column and axis=0 means row
print(df.shape) #3 columns removed so 1000 rows and 11 columns
df.head()

(10000, 11)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

**splitting data into X and Y**

In [4]:
X=df.drop('Exited',axis=1)  #all columns except Exited
Y=df['Exited']              #only the Exited column which is the label column for this data
print(Y.head())
X.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10

**Encoding the string values to numbers**

In [5]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X['Geography']=le.fit_transform(X['Geography'])
X['Gender'] = le.fit_transform(X['Gender'])
X.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,0,0,42,2,0.00,1,1,1,101348.88
1,608,2,0,41,1,83807.86,1,0,1,112542.58
2,502,0,0,42,8,159660.80,3,1,0,113931.57
3,699,0,0,39,1,0.00,2,0,0,93826.63
4,850,2,0,43,2,125510.82,1,1,1,79084.10

**Dividing data into testing and training data**

In [6]:
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,Y,test_size=0.2,random_state=42)

**training without Feature Scalling**

> Add blockquote

In [7]:

model = LogisticRegression()
model.fit(Xtrain,Ytrain)

c:\python\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

 **Testing model**

In [8]:
YPredict=model.predict(Xtest)
accuracy=accuracy_score(Ytest,YPredict)
print("Accuracy : ",accuracy)

Accuracy :  0.799

**Now findin error using LOG_Loss**

In [9]:
Error=log_loss(Ytest, model.predict_proba(Xtest))
print("the error is: ",Error)

the error is:  0.4661152284231277

**N0W training with Feature Scalling**

In [10]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(Xtrain)
X_test=scaler.transform(Xtest)
Y_predict=model.predict(X_test)

c:\python\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [11]:
model=LogisticRegression()
model.fit(X_train,Ytrain)

LogisticRegression()

**Checking accuracy score**

In [12]:
accuracy=accuracy_score(Ytest,Y_predict)
print("Accuracy: ",accuracy)

Accuracy:  0.6075

without feature scalling accuracy was 0.7

**Now Error using Log_Loss**

In [13]:
Error=log_loss(Ytest,model.predict_proba(X_test))

Error

0.4236684576122342